services:
  db_node_1:
    image: mysql:8.0
    container_name: db_node_1
    environment:
      MYSQL_DATABASE: ddb_node_1
      MYSQL_USER: ddb_user
      MYSQL_PASSWORD: ddb_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - db_node_1_data:/var/lib/mysql

  db_node_2:
    image: mysql:8.0
    container_name: db_node_2
    environment:
      MYSQL_DATABASE: ddb_node_2
      MYSQL_USER: ddb_user
      MYSQL_PASSWORD: ddb_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"
    volumes:
      - db_node_2_data:/var/lib/mysql

  db_node_3:
    image: mysql:8.0
    container_name: db_node_3
    environment:
      MYSQL_DATABASE: ddb_node_3
      MYSQL_USER: ddb_user
      MYSQL_PASSWORD: ddb_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3308:3306"
    volumes:
      - db_node_3_data:/var/lib/mysql

volumes:
  db_node_1_data:
  db_node_2_data:
  db_node_3_data:
